### ISSUE TITLE
NVIDIA GPU must need?

### ISSUE THREAD

**Issue by Roger-GOAT** [HantaoShu/DeepSEM#10]
Hi, great software! 
Is the NVIDIA GPU necessary? Or how to deal with the following error. Thanks! 
```
python /home/data/ssy022/DeepSEM/main.py --task celltype_GRN --data_file /home/data/ssy022/cellbender/allday_harmony_process.h5ad --net_file demo_data/GRN_inference/input/500_ChIP-seq_hESC/label.csv --setting new --alpha 0.1 --beta 0.01 --n_epochs 150  --save_name out
Traceback (most recent call last):
  File "/home/data/ssy022/DeepSEM/main.py", line 77, in <module>
    model.train_model()
  File "/home/data/ssy022/DeepSEM/src/DeepSEM_cell_type_specific_GRN_model.py", line 82, in train_model
    vae = VAE_EAD(adj_A_init, 1, self.opt.n_hidden, self.opt.K).float().cuda()
  File "/home/data/ssy022/miniconda3/envs/deepsem/lib/python3.7/site-packages/torch/nn/modules/module.py", line 311, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/data/ssy022/miniconda3/envs/deepsem/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/data/ssy022/miniconda3/envs/deepsem/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/data/ssy022/miniconda3/envs/deepsem/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/data/ssy022/miniconda3/envs/deepsem/lib/python3.7/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/home/data/ssy022/miniconda3/envs/deepsem/lib/python3.7/site-packages/torch/nn/modules/module.py", line 311, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/data/ssy022/miniconda3/envs/deepsem/lib/python3.7/site-packages/torch/cuda/__init__.py", line 178, in _lazy_init
    _check_driver()
  File "/home/data/ssy022/miniconda3/envs/deepsem/lib/python3.7/site-packages/torch/cuda/__init__.py", line 99, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

**Comment by HantaoShu** [comment]
You can replace .cuda() with .cpu() this is related to pytorch document.
