### ISSUE TITLE
AssertionError: Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by bitcometz** [HantaoShu/DeepSEM#3]
hello，I try to run DeepSEM following the toturials on my cluster which has no GPU
```shell
python main.py  --task non_celltype_GRN --data_file demo_data/GRN_inference/input/500_STRING_hESC/data.csv \
        --net_file demo_data/GRN_inference/input/500_STRING_hESC/label.csv --setting new --alpha 100 \
        --beta 1 --n_epoch 90 --save_name out_test
```
and I got the errors:

```
dir exist
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    model.train_model()
  File "path/DeepSEM/src/DeepSEM_cell_type_non_specific_GRN_model.py", line 71, in train_model
    vae = VAE_EAD(adj_A_init, 1, opt.n_hidden, opt.K).float().cuda()
  File "path/env_DeepSEM/lib/python3.7/site-packages/torch/nn/modules/module.py", line 311, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "path/env_DeepSEM/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "path/env_DeepSEM/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "path/env_DeepSEM/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "path/env_DeepSEM/lib/python3.7/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "path/env_DeepSEM/lib/python3.7/site-packages/torch/nn/modules/module.py", line 311, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "path/env_DeepSEM/lib/python3.7/site-packages/torch/cuda/__init__.py", line 178, in _lazy_init
    _check_driver()
  File "path/env_DeepSEM/lib/python3.7/site-packages/torch/cuda/__init__.py", line 99, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

Is there possible I can run DeepSEM on my cluster wihch has no GPU?

Thanks ！！！

**Comment by HantaoShu** [comment]
You can remove all .cuda() used in the code. Please refer pytorch document.

**Comment by bitcometz** [comment]
thanks !!!

**Comment by Roger-GOAT** [comment]
Which document I should find the .cuda() ? Sorry for the easy question...
