### ISSUE TITLE
FileNotFoundError but not mentioning the name of file

### ISSUE THREAD

**Issue by ektapathak08** [HantaoShu/DeepSEM#4]
I am running the  GRN inference step but getting the FileNotFoundError: [Errno 2]. it is not clear that which file is not found.
Please help.

I have installed all the required packages using pip

Thanks in advance
Ekta

python main.py --task celltype_GRN --data_file counts_normazile_log_transformed.csv --setting new --alpha 100 --beta 1 --n_epoch 90 --save_name out1
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    model.train_model()
  File "/home/ekta/Documents/1_ekta_research_work/covid_Pancreas/Qc_doublet_removal/res_4_5/analysis/anticipated_revision/DeepSEM-master/src/DeepSEM_cell_type_specific_GRN_model.py", line 80, in train_model
    dataloader, Evaluate_Mask, num_nodes, num_genes, data, truth_edges, TFmask2, gene_name  = self.init_data()
  File "/home/ekta/Documents/1_ekta_research_work/covid_Pancreas/Qc_doublet_removal/res_4_5/analysis/anticipated_revision/DeepSEM-master/src/DeepSEM_cell_type_specific_GRN_model.py", line 32, in init_data
    Ground_Truth = pd.read_csv(self.opt.net_file, header=0)
  File "/home/ekta/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ekta/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/ekta/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 936, in __init__
    self._make_engine(self.engine)
  File "/home/ekta/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 1168, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/ekta/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 1998, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by HantaoShu** [comment]
It seems you select setting as new instead of test, so you need to provide ground truth label. This setting is used to benchmark performance. So please choice parameter setting as “test”. Code shown in main.py discribe the meaning of each parameter.

**Comment by ektapathak08** [comment]
Hi!
As you suggested that using cpu will take lot of time, mu 8 core machine took more than 24 hrs to complete 2 epochs. And there are 120 epochs in default settings. I terminated the run.

will it be good idea to use DEGs only as input?
What should be criterion for  subsetting gene?
In my dataset , I have around 20k cells.
Please suggest.
